name: Android CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java -cp java NYT-MostPopular

      - name: Running linting checks
        run: ./gradlew runUnitTests

      - name: Running unit tests
        run: ./gradlew runUnitTests

      - name: Running instumentation tests
        run: ./gradlew runInstrumentationTests

      - name: Reclaim Memory
        run: ./gradlew --stop && jps|grep -E 'KotlinCompileDaemon|GradleDaemon'| awk '{print $1}'| xargs kill -9

      - name: Final Linting Checks
        run: ./gradlew check --stacktrace

      - name: Build project with Gradle
        run: ./gradlew build
